from . import res_users_datamodels
from . import res_partner_datamodels
from . import res_company_datamodels
from . import res_currency_datamodels
from . import fleet_vehicle_datamodels
from . import fleet_vehicle_assignation_log_datamodels
from . import fleet_vehicle_log_contract_datamodels
from . import fleet_service_type_datamodels
from . import fleet_vehicle_state_datamodels
from . import fleet_vehicle_tag_datamodels
from . import fleet_vehicle_model_brand_datamodels
from . import fleet_vehicle_model_datamodels
from . import fleet_vehicle_log_services_datamodels
from . import fleet_vehicle_odometer_datamodels
