from . import res_users_datamodels
from . import res_partner_datamodels
from . import res_currency_datamodels
from . import fleet_vehicle_datamodels
from . import fleet_vehicle_assignation_log_datamodels
from . import fleet_vehicle_log_contract_datamodels
from . import fleet_service_type_datamodels
from . import fleet_vehicle_state_datamodels
from . import fleet_vehicle_tag_datamodels
from . import fleet_vehicle_model_brand_datamodels
from . import fleet_vehicle_model_datamodels
from . import vehicle_short_info
from . import vehicle_info
from . import vehicle_search_param
from . import vehicle_odometer
from . import vehicle_log_services
