from . import service
from . import fleet_vehicle_assignation_log_services
from . import fleet_vehicle_log_contract_services
from . import fleet_service_type_services
from . import fleet_vehicle_state_services
from . import fleet_vehicle_tag_services
from . import fleet_vehicle_model_brand_services
from . import fleet_vehicle_model_services
from . import fleet_vehicle_log_services_services
from . import vehicle_services
from . import vehicle_image_services
from . import vehicle_odometer
